### PR TITLE
Fix 'gbk' codec can't encode character '\u200b' when resolve context

### LINKED ISSUE #1507: 'gbk' codec can't encode character '\u200b' when resolve context
'gbk' codec can't encode character '\u200b' when resolve context

**Environment**
* Windows Server 2012
* Rez 2.112.0
* Python-3.9.13

**To Reproduce**
When we build some packages on the CI machine, it is easy to encounter the errors in the following logs. The system language of our CI machine is English.
But some resolve context environments may contain Chinese character strings

**Actual behavior**
```cmd
[merge-request] Invoking custom build system...
[merge-request] Running build command: python c:\data\orange-ci\git\ckpt_roop_models\coding-ci-u2o-1h4kfh45b-001\workspace/rezbuild.py install
[merge-request] Traceback (most recent call last):
[merge-request]   File "S:\Python-3.9\Lib\runpy.py", line 197, in _run_module_as_main
[merge-request]     return _run_code(code, main_globals, None,
[merge-request]   File "S:\Python-3.9\Lib\runpy.py", line 87, in _run_code
[merge-request]     exec(code, run_globals)
[merge-request]   File "S:\rez\2.112.0\platform-windows\Scripts\rez_exe\rez.exe\__main__.py", line 7, in <module>
[merge-request]   File "S:\rez\2.112.0\platform-windows\rez\cli\_entry_points.py", line 69, in run_rez
[merge-request]     return run()
[merge-request]   File "S:\rez\2.112.0\platform-windows\rez\cli\_main.py", line 191, in run
[merge-request]     returncode = run_cmd()
[merge-request]   File "S:\rez\2.112.0\platform-windows\rez\cli\_main.py", line 183, in run_cmd
[merge-request]     return func(opts, opts.parser, extra_arg_groups)
[merge-request]   File "S:\rez\2.112.0\platform-windows\rez\cli\build.py", line 158, in command
[merge-request]     builder.build(install_path=opts.prefix,
[merge-request]   File "S:\rez\2.112.0\platform-windows\rezplugins\build_process\local.py", line 52, in build
[merge-request]     num_visited, build_env_scripts = self.visit_variants(
[merge-request]   File "S:\rez\2.112.0\platform-windows\rez\build_process.py", line 208, in visit_variants
[merge-request]     result = func(variant, **kwargs)
[merge-request]   File "S:\rez\2.112.0\platform-windows\rezplugins\build_process\local.py", line 336, in _build_variant
[merge-request]     build_result = self._build_variant_base(
[merge-request]   File "S:\rez\2.112.0\platform-windows\rezplugins\build_process\local.py", line 248, in _build_variant_base
[merge-request]     build_result = self.build_system.build(
[merge-request]   File "S:\rez\2.112.0\platform-windows\rezplugins\build_system\custom.py", line 214, in build
[merge-request]     retcode, _, _ = context.execute_shell(
[merge-request]   File "S:\rez\2.112.0\platform-windows\rez\resolved_context.py", line 1045, in _check
[merge-request]     return fn(self, *nargs, **kwargs)
[merge-request]   File "S:\rez\2.112.0\platform-windows\rez\resolved_context.py", line 1445, in execute_shell
[merge-request]     f.write(context_code)
[merge-request] UnicodeEncodeError: 'gbk' codec can't encode character '\u200b' in position 756: illegal multibyte sequence
``

### PR DESCRIPTION
**Pull request by loonghao**
This PR is try to fix #1507

### CODE REVIEW

**Comment by maxnbk** [comment]
The io.open / codecs switch causes the py2.7 tests to fail, presently. Could that be wrapped per version?

Something like?
```
from rez.vendor.six import six

# http://python3porting.com/problems.html#replacing-userdict
if six.PY2:
    import codecs.open as open
else:
    import io.open as open

# [...]

with open() # etc
```

**Comment by loonghao** [comment]
> The io.open / codecs switch causes the py2.7 tests to fail, presently. Could that be wrapped per version?io.open / codecs 开关目前会导致 py2.7 测试失败。可以按版本包装吗？
> 
> Something like? 像什么？
> 
> ```
> from rez.vendor.six import six
> 
> # http://python3porting.com/problems.html#replacing-userdict
> if six.PY2:
>     import codecs.open as open
> else:
>     import io.open as open
> 
> # [...]
> 
> with open() # etc
> ```
Test failed in CI same with this [issues#1502](https://github.com/AcademySoftwareFoundation/rez/issues/1502)


`io.open` should also work well in python-2.7, please let me know if there is anything else I missed, thanks.

Reference:
https://code.activestate.com/lists/python-list/681909

**Comment by loonghao** [comment]
@maxnbk I have already updated the PR. Please take your time to review it again and let me know if there is anything else that needs to be modified. Thank you.

**Review by maxnbk — APPROVED** [review]

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
Thank you @loonghao ! We merged your change and it should be released in the next release.

**Pull request merged**
