### PR TITLE
Convert wiki to Sphinx/ReadTheDocs (REP-004 part 1)

### LINKED ISSUE #1292: REP-004: Documentation Improvements
There's been a some discussions around Rez's documentation. Both in terms of ["what can we document better"](https://github.com/nerdvegas/rez/discussions/1277) as well as ["how can we improve what we have documented, already"](https://academysoftwarefdn.slack.com/archives/C0321B828FM/p1650437035544429)

GitHub Discussion: #1293 

This REP will focus on the latter portion. From group discussion, these key desires and improvements have been identified

- [ ] REP-004.1 - Versioned Sphinx documentation
    - [ ] The majority choice is to build + integrate Rez documentation using readthedocs.io
- [ ] REP-004.2 - Better / Fully automated Rez API documentation
- [ ] REP-004.3 - Unity between Rez's wiki pages and the Rez Sphinx documentation
    - [ ] Eventually deprecate GitHub Pages, following a separate audit once contributors are happy with the Sphinx results
- [ ] REP-004.4 - Documentation previews In PRs
- [ ] REP-004.5 - Ensure clean Sphinx builds

## REP-004.1 - Versioned Sphinx documentation

The desire is to have documentation per-Rez-version **as well as** a "latest" / "stable" location which is consistent with Rez's latest release. Leveraging readthedocs.io to handle this will be a key point of this work.

## REP-004.2 - Better / Fully automated Rez API documentation

Rez API documentation is currently out of date and manually generated. Use `autosummary`, `sphinx-apidoc`, or another, similar technology to make the API pages on the fly, so they're always kept up to date.

## REP-004.3 - Unity between Rez's wiki pages and the Rez Sphinx documentation

Rez Sphinx documentation and Rez GitHub pages (wiki markdown) are currently separate. Making them as a single source will encourage more people to make documentation as well as make the documentation more meaningful, because hand-written documentation will be able to directly link to API code and vice versa.

## REP-004.4 - Documentation Previews In PRs

Currently, hand-written documentation or API documentation changes which are still in PR must be reviewed locally in order to see the "rendered" result, which is not ideal. Assuming REP-004.1 is successfully implemented with readthedocs.io, we could leverage readthedocs.io's  PR documentation preview service. (See https://docs.readthedocs.io/en/stable/pull-requests.html for details)

## REP-004.5 - Ensure clean Sphinx builds
Requires: **REP-004.1**

Rez's Sphinx documentation currently builds with about 90 warnings and a few error. A general clean-up would be greatly appreciated. Also, once Sphinx is better supported, we'll be able to go back in and improve our use of Sphinx roles (`:ref:`, `:doc:`, `:mod:`, `:func:`, etc) as a separate, parallel effort.

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
Closes #1292 (at least partially). Also relates to https://github.com/AcademySoftwareFoundation/rez/discussions/1277.

This PR converts our GitHub wiki to Sphinx. It will be automatically built by ReadTheDocs and each PR will be built and will have a preview (see the actions on the PR for the link of the preview).

Preview link: https://rez--1522.org.readthedocs.build/en/1522/

Note that this is almost a dumb conversion, in the sense that there isn't new documentation. Changes are:

* The Python API docs and the docs for rez are now all in one place.
* All environment variables are now fully documented (even for the settings), except for the `*_JSON` variables.
* I added a huge amount of cross references between all the pages. Settings can now be easily references (and they are), environment variables can also be referenced.
* Settings now have proper type hints (where possible) in the docs (not in the code).
* The rex functions are also typed hinted in the docs (not the code).
* The generation process for the settings docs is fully integrated in Sphinx, which means that it's now a single step process step process :)
* The documentation is now fully searchable (thanks to ReadTheDocs).
* The order and grouping in the table of content was re-organized to help finding what you are looking for and also helping our new users discover pages more "naturally" (it's probably the wrong term, but it's the only one that comes to mind).

There is a few pages that were left out:
* The glossary, because I felt like it was redundant.
* ~The rez-pip docs, because the new rez-pip2 is coming soon.~ I converted it.
* ~the CLI docs, because I felt they weren't that useful. To be useful, it would require to use sphinx directives for proper cross-referencing in the docs. This would need some custom code in the `conf.py` file.~ The CLI docs are now automatically generated.

I could probably add the glossary and the rez-pip docs if others feel like they are important enough.

As it is right now, I think we could try it and see how it goes. I personally think that's it's already a good improvement over what we have.

TODO:
* [ ] Determine if we want to remove the `wiki` directory now or in a seperate PR.
* [ ] Remove `wiki` workflow if we remove the `wiki` directory.
* [ ] If we remove the `wiki` directory, disable the wiki entirely on the repo after the merge.

### CODE REVIEW

**Comment by davidlatwe** [comment]
The new doc looks awesome! And really great that it comes with light/dark mode switch.

I have a suggestion for the final polishing work. My system uses dark mode, and this is what I saw in first page:

image

The black outline and arrows are not really easy to see.

I am thinking each image we used in the doc should have 2 versions, one for light mode and one for the dark. Or just one, with a solid backgound that fits in both modes.

I can help with those images if you need, just let me know. 👍🏼

**Comment by JeanChristopheMorinPerso** [comment]
Hi @davidlatwe ! Thanks for taking a look!

Regarding dark mode problems with the images, I indeed saw that but deciced that it could be improved in a subsequent PR. Furo supports dark/light figures (https://pradyunsg.me/furo/reference/images/#different-images-for-dark-light-mode), so it would be possible to have a dark and light version of the images.

If you feel like contributing new diagrams in dark and light mode, I can definitely add the to the PR though!

**Comment by JeanChristopheMorinPerso** [comment]
@davidlatwe I made an attempt at changing the images/diagrams using CSS. They now render properly when viewing in dark mode. It's not perfect, but it avoids having to deal with duplicating the diagrams for each theme.

Let me know what you think.

**Comment by davidlatwe** [comment]
Thanks @JeanChristopheMorinPerso !

I noticed this, the images were not inverted when the theme is set to respect system preference. (My system has set to dark)

image

But I suppose that should be fixed by adding [`@media (prefers-color-scheme: dark)`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to the selector. (didn't build the doc on my end 😅 )

```css
@media (prefers-color-scheme: dark)
body[data-theme=dark] .rez-diagram {
    ...
}
```

Anyway, I like this solution 👍🏼

**Comment by JeanChristopheMorinPerso** [comment]
Alright, I made the change @davidlatwe. I tested all modes (manual overrides, OS overrides, etc) and everything seems to be working now.

**Comment by JeanChristopheMorinPerso** [comment]
@davidlatwe I integrated your commit and the CLA and DCO checks are failing. I see two ways to fix this:
1. One is for you to authorize me to add the appropriate "Signed-off-by: Author Name <authoremail@example.com>" bit in your commit and you'll have to sign the CLA.
2. I can take ownership of the commit and put you as co-author (So I would add "Co-authored-by: David Lai <your email>".

Do you have a preference?

**Comment by davidlatwe** [comment]
This is a reply for the Slack chat https://academysoftwarefdn.slack.com/archives/C0321B828FM/p1693697597478139

## Feedback (My 2 cents)

### Is it readable?

You bet. 👍🏼 

### Are you able to search and find what you need (for example, try searching for settings, environment variables, etc)

Yes, but not perfect.🤔  When I was trying to search `include`, the decorator for sharing code across packages, the search results were not really ideal. 

<details> <summary> Screenshot </summary>

image

</details>

Same for `early`.

<details> <summary> Screenshot </summary>

image

</details>

The top 3 search results were Python API entries, which I think they are too advance for most cases. Secondly, when you click one of the results, the page doesn't scroll to the expected paragraph, it only brings you to that page.

image

### Is the table of content of the left side clear and intuitive (by that I mean the grouping and ordering, etc)?

There should have a "Resolving Packages" page between "Building Packages" and "Context" page. Perhaps we should breakdown "Basic Concepts" into smaller chunks?

### What do you think of [configuration settings](https://rez--1522.org.readthedocs.build/en/1522/configuring_rez.html#configuration-settings), is it easy to read and understand?

It's good that the doc also mentioned the equivalent environment variable, but would be better if we can have those env var displayed with different color, e.g. gray.

image


### Same for [package attributes](https://rez--1522.org.readthedocs.build/en/1522/package_definition.html#package-attributes) and [package commands objects](https://rez--1522.org.readthedocs.build/en/1522/package_commands.html#objects).

These are awesome! So much better with typing and example.

<br>

**Comment by davidlatwe** [comment]
> @davidlatwe I integrated your commit and the CLA and DCO checks are failing. I see two ways to fix this:
> 
> 1. One is for you to authorize me to add the appropriate "Signed-off-by: Author Name [authoremail@example.com](mailto:authoremail@example.com)" bit in your commit and you'll have to sign the CLA.
> 2. I can take ownership of the commit and put you as co-author (So I would add "Co-authored-by: David Lai ".
> 
> Do you have a preference?

Didn't notice that! I just clicked the link from that EasyCLA and signed it, so all should be good? Both options work for me but since I have CLA signed, option 1 would be better I guess? 🤔

**Comment by JeanChristopheMorinPerso** [comment]
Alright, DCO is fixed.

**Comment by JeanChristopheMorinPerso** [comment]
Thanks for the feedback (and the help too :))!

>>Are you able to search and find what you need (for example, try searching for settings, environment variables, etc)
>
>Yes, but not perfect.🤔 When I was trying to search include, the decorator for sharing code across packages, the search results were not really ideal.

Yeah, I saw that too. By default RTD indexes everything in ElasticSearch and they hijack the search bar to read from ElasticSearch (see https://docs.readthedocs.io/en/stable/server-side-search/index.html). But for whatever reason it doesn't seem to be the case right now. I'm guessing it's because we haven't released the docs to the default version. They probably don't index all commits coming for PRs (because it would obviously be cost and resource prohibitive). I'm crossing my fingers that it'll improve once we merge this in master.

>The top 3 search results were Python API entries, which I think they are too advance for most cases. Secondly, when you click one of the results, the page doesn't scroll to the expected paragraph, it only brings you to that page.

Like I said, I'm guessing this is related to the fact that the PR isn't indexed in ElasticSearch. As for the Python API stuff, we could de-prioritize the Python API using https://docs.readthedocs.io/en/stable/config-file/v2.html#search-ranking. In fact I tried it and it wasn't having any effect (again probably because they don't index PR builds).

>There should have a "Resolving Packages" page between "Building Packages" and "Context" page. Perhaps we should breakdown "Basic Concepts" into smaller chunks?

Indeed. The current "Basic Concepts" page is annoying me (and I never liked it). It mixes concepts with implementation details, and other stuff like tutorials (resolving an environment). I was hoping that we could review all this in a second phase though. I interpret your reply as "the ordering and grouping is fine but we should split some pages and re-group things", is that correct?

>>What do you think of [configuration settings](https://rez--1522.org.readthedocs.build/en/1522/configuring_rez.html#configuration-settings), is it easy to read and understand?
>
>It's good that the doc also mentioned the equivalent environment variable, but would be better if we can have those env var displayed with different color, e.g. gray.

Thanks! It's been annoying me too. I actually spent a day trying to improve this without involving CSS and couldn't find a solution that satisfied me. I kind of know what I want, but I'm not sure how simple it would be to implement and would require quite a bit of custom Sphinx code (I think), and I don't even know if what I want is doable. And I already have 350 lines of code in my custom sphinx extension... I think I'll open an issue on the Sphinx repo to ask for help.

**Review by instinct-vfx — APPROVED** [review]
This is a huge step forward and my vote is to get this merged asap and make it available to a wider audience. We can then start iterating and further improving! Thanks a lot @JeanChristopheMorinPerso !

**Pull request merged**
