### PR TITLE
Fix 1255-possible-regression-appendenv-in-powershell-fails-if-env-variable-does-not-exist-already

### PR DESCRIPTION
**Pull request by instinct-vfx**
There is a regression that was introduced by #1176 
The nested `Get-ChildItem` call fails with an error if the Variable does not exist. Old behaviour restored without reverting the fix by adding `-ErrorAction SilentlyContinue`

### CODE REVIEW

**Comment by instinct-vfx** [comment]
Fixes #1255

**Review by JeanChristopheMorinPerso — APPROVED** [review]
lgtm

**Comment by SitiSchu** [comment]
What needs to be done to get this merged?

**Comment by bpabel** [comment]
I would value a comment explaining why the command is set to silently ignore errors. It's one of those things I could see getting removed in the future if no one remembers why it was added.

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Review by maxnbk — APPROVED** [review]

**Pull request merged**
