### PR TITLE
Allow changes to employment in GOVERNANCE.md to be merged without unanimous approval

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
Like the title says.

### CODE REVIEW

**Review by maxnbk — APPROVED** [review]

**Review by instinct-vfx — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
@bpabel @nerdvegas

**Review by nerdvegas — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
@bpabel Are you good with this change?

**Comment by bpabel** [comment]
Looks good to me

**Comment by JeanChristopheMorinPerso** [comment]
Thanks @bpabel . I rebased to fix the conflict. I'll merge the PR now.

**Pull request merged**
