### PR TITLE
add missing backslashes to gitbash shell executable path

### LINKED ISSUE #1302: sheband and executable paths incorrect in gitbash
When creating a rez environment with gitbash on Windows, the shebang and executable paths use a single slash which gets escaped and causes the paths to be incorrect.

**Environment**
* OS "windows 10"
* Rez version "2.109.0"
* Rez python version "3.7"

**To Reproduce**
1. Open a gitbash shell on Windows
2. Run a `rez-env`

**Expected behavior**
Taken into a rez environment.

**Actual behavior**
Command not found error

### PR DESCRIPTION
**Pull request by amorphousWaste**
Fixes #1302

### CODE REVIEW

**Comment by JeanChristopheMorinPerso** [comment]
@amorphousWaste Can you undo the version bump please? It's normally preferable to not update it and let the maintainers change the version instead. Thanks!

**Comment by JeanChristopheMorinPerso** [comment]
Also, since the repo was moved to the ASWF, you will need to sign the CLA, see https://github.com/AcademySoftwareFoundation/rez/pull/1303#issuecomment-1144156270.

Additionally, you also need to sign your commits, see https://github.com/AcademySoftwareFoundation/rez/pull/1303/checks?check_run_id=6715395153 for instructions on how to do that.

Let us know if you have any questions!

**Comment by amorphousWaste** [comment]
I reverted the version and I'm waiting on my boss to approve me for contributions to the repo. Once that is done, I'll follow the instructions to retroactively sign the commits.

**Comment by amorphousWaste** [comment]
Should I change the branch name?

**Comment by amorphousWaste** [comment]
I retroactively signed my commits following the instructions, but it looks like one got left out. I followed the instructions again and now it looks like it doesn't like an email address. Sorry, but can anyone help me with this?

**Comment by JeanChristopheMorinPerso** [comment]
DCO says:
```
Commit sha: [0880ee4](https://github.com/AcademySoftwareFoundation/rez/pull/1303/commits/0880ee4d5c6b4e7ec515219eb35215d10db3e561), Author: github.com/nerdvegas, Committer: amorphousWaste; nerdvegas@a043125d43e01f8c1ae440f0086f712c86b67214 is not a valid email address.
```

I don't know how that commit made it into the PR, but I would simply remove that commit as these commits are normally created from scheduled jobs that are not supposed to run on PRs.

By removing that commit from your branch, I think it will solve your issues.

**Comment by nerdvegas** [comment]
Ah crap I know what that is. The benchmark CI does this, it commits the
latest benchmark results into the repo. It won't be doing DCO yet, and it
probably wasn't configured with a valid email address.

I'll see how I'm going tonight, might be able to put in a fix for this. It
should be reasonably simple though.

**Comment by JeanChristopheMorinPerso** [comment]
@nerdvegas Yep, that's what I understood. What's not clear is how the commit got into this PR.

**Comment by nerdvegas** [comment]
Yeah same actually. OP did you perhaps remerge with master at some point
after you did the retro signoff?
A

**Comment by amorphousWaste** [comment]
I don't think so. There wouldn't have been a reason to.

**Comment by nerdvegas** [comment]
See comment on https://github.com/AcademySoftwareFoundation/rez/issues/1302

ps - @amorphousWaste were you able to sign onto EasyCLA? And any more word on what's going on wrt DCO? I'm going to merge https://github.com/AcademySoftwareFoundation/rez/pull/1319 soon, which hopefully will help at least (if it's the benchmark CI commit causing the problem that is).

**Comment by amorphousWaste** [comment]
I was finally able to jump back on this. I removed the config option and addes additional functions into the shells for returning paths in different styles as needed.

**Comment by amorphousWaste** [comment]
I'm not sure why there is still an EasyCLA block. Everything should be signed off. Would anyone be able to assist?

**Comment by JeanChristopheMorinPerso** [comment]
See https://github.com/AcademySoftwareFoundation/rez/pull/1303#issuecomment-1147962415. You have commits that are not supposed to be there. You also need to fix the conflict.

**Comment by amorphousWaste** [comment]
Probably dumb question, how do I know what commits shouldn't be there?

**Comment by JeanChristopheMorinPerso** [comment]
If you look at the commits tab, all the commits that are not authored by you shouldn't be there. I have no idea how they ended up there. But fortunately, there is multiple ways to fix that:

* You can manually remove them from your branch if you do an interactive rebase and drop the commits you want to drop.
* You can delete your local branch and create a new one with the same name, and cherry-pick the commits you want.
* Close this PR, create a new branch and cherry-pick you commits, create a new PR.
* Or any other ways that you can come up with (some people like to get creative in their usage of git)

Also, could you add a description to the pull request please? Your latest commits changed what you previously did and it's not super clear how it's all supposed to work and if it addresses [my comment](https://github.com/AcademySoftwareFoundation/rez/issues/1302#issuecomment-1157092791) and [Allan's comment](https://github.com/AcademySoftwareFoundation/rez/issues/1302#issuecomment-1159823297).

In general, it's always good to put a nice descriptive description that explains the thought process and why the changes were made the way you made them.

**Comment by amorphousWaste** [comment]
I think I've hecked up this PR too much, so at the risk of only making things worse I'm going to close this and make a new one.

**Pull request closed without merging**
