### PR TITLE
Add REZ_USED_LOCAL_RESOLVE context environment variable

### LINKED ISSUE #1371: Expose an environment flag if any locally installed packages were resolved in the current context
Looking for an easy way to know if I'm in a "development" environment using an environment variable
The consensus on the slack was to evaluate common environment variables for the rez local install path but that feels like both double handling data the resolver probably already has and has the potential to miss uncommon packages

**Motivation**
Exposing this info as an environment variable makes it easy to know if you're in a local development environment and easy to feed that into logging/monitoring

### PR DESCRIPTION
**Pull request by JoshkVFX**
Populate the environment variable "REZ_USED_LOCAL_RESOLVE" in the same style as REZ_USED_EPH_RESOLVE for any packages resolved to a local destination

Closes #1371 

Let me know if there's a version number I need to bump or something

### CODE REVIEW

**Review by JeanChristopheMorinPerso — APPROVED** [review]
LGTM. That's exactly what I was imagining.

**Review by nerdvegas — DISMISSED** [review]
I'm ok with what's been done here, but the docs need updating here: https://github.com/AcademySoftwareFoundation/rez/wiki/Environment-Variables#context-environment-variables

Take care to note that this new envvar will contain a subset of what's already in REZ_USED_RESOLVE.

You just need to update this file, the wiki will be updated for you: https://github.com/AcademySoftwareFoundation/rez/blob/master/wiki/pages/Environment-Variables.md

**Comment by JoshkVFX** [comment]
@nerdvegas How's that look?

**Comment by JeanChristopheMorinPerso** [comment]
Thanks for documenting it! To me it looks great.

**Review by bpabel — APPROVED** [review]
LGTM

**Review by maxnbk — APPROVED** [review]

**Pull request merged**
