### PR TITLE
add rez-maintainers as codeowners

### PR DESCRIPTION
**Pull request by maxnbk**
Signed-off-by: Stephen Mackenzie <maxnbk@users.noreply.github.com>

### CODE REVIEW

**Review by bpabel — APPROVED** [review]

**Comment by maxnbk** [comment]
I'm leaving @nerdvegas on the list separately as a backup to see how marking the group rather than individuals works, in case something is wrong with that (though the docs indicate it should work)

**Review by instinct-vfx — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
@maxnbk could we simplify the file and just make the whole TSC the owner of all files?

**Review by nerdvegas — APPROVED** [review]

**Comment by maxnbk** [comment]
> @maxnbk could we simplify the file and just make the whole TSC the owner of all files?

Maybe? But the separation may become useful later if we decide that not everyone wants to see every kind of PR, or that maybe a specific team is in charge of, say, the solver. I'll keep the update to a group ownership update for now, and check to see if we can collapse it as a separate one, because my main concern here is that each TSC member approves being added to every PR by default, and then moving on from there if there is an objection.

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
Alright, make sense. I approved and merged since everybody approved.

Thanks @maxnbk !

**Pull request merged**
